%C = intersection_vectors(k, Vtemp)
%--------------------------------------------------------------------------
%Finds the vectors tha solve the equation v_i1=...=v_id for all d
%collections of curves. These are exactly the vectors that are generated by
%the intersection of these d curves.
%
%Version 1.0
%Date: 21/06/2013
%
%Input:
%   k: levels of sparsity for each PC, e.g. k = [5, 4, 3, 2, 5]
%   Vtemp: nxd matrix
%Output: 
%   C: (d+1)x(n choose d) matrix where each column is a vector that
%   corresponds to an intersection of d curves. The last element of each
%   column corresponds to one of the curves in the intersection.
%--------------------------------------------------------------------------

function C = intersection_vectors(k, Vtemp)
d = size(Vtemp,2);
n = size(Vtemp,1);
combs = nchoosek(1:n, d);
C = zeros(d+1, length(combs)); % C will store all intersection vectors
% calculate intersection points of the first k+1 curves
p = 1;
for i = 1:size(combs,1)
    V_inter = Vtemp(combs(i,:),:);
    signs = [-ones(2^(d-1),1) 2*(dec2bin(0:2^(d-1)-1)-48)-1];
    for j=1:2^(d-1)
        V_inter_signed = diag(signs(j,:))*V_inter;
        [temp1 temp2 Vr] = svd(V_inter_signed(2:end,:)-kron(ones(d-1,1),V_inter_signed(1,:)));
        C(:,p) = [Vr(:, end); combs(i,1)]; % store the intersection vector and one of the intersecting curves
        p = p+1;
    end       
end


